name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jamescurtin/isort-action@master
        with:
          configuration: "-l 127"
      - uses: psf/black@stable
        with:
          options: "--line-length 127"
